import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  UseGuards,
  Request,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiParam,
  ApiBody,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { Roles } from '../common/decorators/roles.decorator';
import { UserRole } from '../common/enums/user-role.enum';
import { AlertsService } from './alerts.service';
import { CreateAlertDto } from './dto/create-alert.dto';
import { UpdateAlertDto } from './dto/update-alert.dto';
import { MarkReadAlertDto } from './dto/mark-read-alert.dto';
import { AssignAlertDto } from './dto/assign-alert.dto';
import { ResolveAlertDto } from './dto/resolve-alert.dto';

@ApiTags('Alerts')
@ApiBearerAuth('JWT-auth')
@Controller('alerts')
@UseGuards(JwtAuthGuard, RolesGuard)
export class AlertsController {
  constructor(private readonly alertsService: AlertsService) {}

  @Post()
  @Roles(UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({
    summary: 'Create alert',
    description: 'Create a new alert manually. Most alerts are auto-generated by the system.',
  })
  @ApiBody({ type: CreateAlertDto })
  @ApiResponse({ status: 201, description: 'Alert created successfully' })
  create(@Body() createAlertDto: CreateAlertDto, @Request() req) {
    // Asignar user_id automáticamente si no se proporciona
    const alertData = {
      ...createAlertDto,
      user_id: createAlertDto.user_id || req.user?.id,
    };
    return this.alertsService.createAlert(alertData);
  }

  @Get()
  @Roles(UserRole.OPERATOR, UserRole.SUPERVISOR, UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({
    summary: 'Get all alerts',
    description: 'Retrieve all alerts. Operators can only see their own alerts.',
  })
  @ApiResponse({ status: 200, description: 'List of alerts' })
  findAll(@Request() req) {
    return this.alertsService.findAll(req.user);
  }

  @Get('unread')
  @Roles(UserRole.OPERATOR, UserRole.SUPERVISOR, UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({ summary: 'Get unread alerts' })
  @ApiResponse({ status: 200, description: 'List of unread alerts' })
  findUnread(@Request() req) {
    return this.alertsService.findUnread(req.user);
  }

  @Get(':id')
  @Roles(UserRole.OPERATOR, UserRole.SUPERVISOR, UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({ summary: 'Get alert by ID' })
  @ApiParam({ name: 'id', description: 'Alert UUID', type: String, format: 'uuid' })
  @ApiResponse({ status: 200, description: 'Alert details' })
  @ApiResponse({ status: 404, description: 'Alert not found' })
  findOne(@Param('id') id: string, @Request() req) {
    return this.alertsService.findOne(id, req.user);
  }

  @Patch(':id')
  @Roles(UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({ summary: 'Update alert' })
  @ApiParam({ name: 'id', description: 'Alert UUID', type: String, format: 'uuid' })
  @ApiBody({ type: UpdateAlertDto })
  @ApiResponse({ status: 200, description: 'Alert updated successfully' })
  update(@Param('id') id: string, @Body() updateAlertDto: UpdateAlertDto, @Request() req) {
    return this.alertsService.update(id, updateAlertDto, req.user);
  }

  @Patch(':id/mark-read')
  @Roles(UserRole.OPERATOR, UserRole.SUPERVISOR, UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({ summary: 'Mark alert as read/unread' })
  @ApiParam({ name: 'id', description: 'Alert UUID', type: String, format: 'uuid' })
  @ApiBody({ type: MarkReadAlertDto })
  @ApiResponse({ status: 200, description: 'Alert marked as read' })
  markAsRead(@Param('id') id: string, @Body() markReadDto: MarkReadAlertDto, @Request() req) {
    return this.alertsService.markAsRead(id, markReadDto, req.user);
  }

  @Post(':id/assign')
  @Roles(UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({
    summary: 'Assign alert to a user',
    description: 'Assign an alert to a user. Status will change to IN_REVIEW. Only Administration and Direction can assign alerts.',
  })
  @ApiParam({ name: 'id', description: 'Alert UUID', type: String, format: 'uuid' })
  @ApiBody({ type: AssignAlertDto })
  @ApiResponse({ status: 200, description: 'Alert assigned successfully' })
  @ApiResponse({ status: 403, description: 'Only Administration and Direction can assign alerts' })
  @ApiResponse({ status: 404, description: 'Alert not found' })
  assign(@Param('id') id: string, @Body() assignDto: AssignAlertDto, @Request() req) {
    return this.alertsService.assign(id, assignDto, req.user);
  }

  @Post(':id/resolve')
  @Roles(UserRole.OPERATOR, UserRole.SUPERVISOR, UserRole.ADMINISTRATION, UserRole.DIRECTION)
  @ApiOperation({
    summary: 'Resolve alert',
    description: 'Resolve an alert. Status will change to RESOLVED. Assigned user, Administration, or Direction can resolve.',
  })
  @ApiParam({ name: 'id', description: 'Alert UUID', type: String, format: 'uuid' })
  @ApiBody({ type: ResolveAlertDto })
  @ApiResponse({ status: 200, description: 'Alert resolved successfully' })
  @ApiResponse({ status: 403, description: 'You do not have permission to resolve this alert' })
  @ApiResponse({ status: 404, description: 'Alert not found' })
  resolve(@Param('id') id: string, @Body() resolveDto: ResolveAlertDto, @Request() req) {
    return this.alertsService.resolve(id, resolveDto, req.user);
  }

  @Delete(':id')
  @Roles(UserRole.DIRECTION)
  @ApiOperation({
    summary: 'Delete alert',
    description: 'Delete an alert. Only Direction can delete alerts.',
  })
  @ApiParam({ name: 'id', description: 'Alert UUID', type: String, format: 'uuid' })
  @ApiResponse({ status: 200, description: 'Alert deleted successfully' })
  @ApiResponse({ status: 403, description: 'Only Direction can delete alerts' })
  remove(@Param('id') id: string, @Request() req) {
    return this.alertsService.remove(id, req.user);
  }
}

